### PR TITLE
fix(review): small tweeks

### LINKED ISSUE #189: Sort screenshot diffs using an alphanumeric order
That order comes after the score one.

### PR DESCRIPTION
**Pull request by oliviertassinari**
Closes #189.

### CODE REVIEW

File: src/review/routes/profile/Profile.js [hunk 1]
```diff
@@ -42,17 +54,15 @@ function Profile(props) {
               <Layout item>
                 <Avatar
                   src={`https://github.com/${profileName}.png?size=300`}
-                  style={{ width: 120, height: 120 }}
+                  className={classes.avatar}
```
Comment (neoziro) [inline src/review/routes/profile/Profile.js]: J'avais eu la flemme :x

File: src/server/graphql/BuildType.js [hunk 2]
```diff
@@ -60,7 +60,11 @@ const BuildType = new GraphQLObjectType({
     screenshotDiffs: {
       description: 'Get the diffs for a given build.',
       type: new GraphQLList(ScreenshotDiffType),
-      resolve: build => build.$relatedQuery('screenshotDiffs').orderBy('score', 'desc'),
+      resolve: source => source
+        .$relatedQuery('screenshotDiffs')
+        .innerJoin('screenshots', 'screenshots.id', 'screenshot_diffs.baseScreenshotId')
```
Comment (oliviertassinari) [inline src/server/graphql/BuildType.js]: We have quite some N+1 query with that one. That's quick and dirty.

Comment (neoziro) [inline src/server/graphql/BuildType.js]: Yes, but it can be easily fixed with GraphQL. If the performance is correct, sounds good for me.
