### PR TITLE
Fix rights on public and private repositories

### LINKED ISSUE #163: Sync should remove deleted repositories
As a user, when a repo is deleted, it is removed from my repositories.

### PR DESCRIPTION
**Pull request by neoziro**
All rights are now fixed.

Also closes #163.

### CODE REVIEW

File: src/modules/synchronizer/GitHubSynchronizer.js [hunk 1]
```diff
@@ -15,51 +15,61 @@ class GitHubSynchronizer {
...
         organizationId: organizationIdByRepositoryId[githubRepository.id],
         userId: userIdByRepositoryId[githubRepository.id],
+        private: githubRepository.private,
       }
 
       let [repository] = await Repository.query().where({ githubId: githubRepository.id })
 
       if (repository) {
-        await repository.$query().patch(data)
+        await repository.$query().patchAndFetch(data)
```
Comment (oliviertassinari) [inline src/modules/synchronizer/GitHubSynchronizer.js]: What's the fetch for?

File: src/modules/synchronizer/GitHubSynchronizer.js [hunk 2]
```diff
@@ -15,51 +15,61 @@ class GitHubSynchronizer {
...
-        })
-      }
+      return repository
     }))
 
     if (this.github.hasNextPage(githubRepositories)) {
-      await this.synchronizeRepositories({ page: page + 1 })
+      const nextPageData = await this.synchronizeRepositories({ page: page + 1 })
+
+      nextPageData.repositories.forEach((repository) => {
```
Comment (oliviertassinari) [inline src/modules/synchronizer/GitHubSynchronizer.js]: `_.unionBy` ?

File: src/modules/synchronizer/GitHubSynchronizer.js [hunk 3]
```diff
@@ -94,42 +104,33 @@ class GitHubSynchronizer {
...
+              .find(owner => owner.githubId === githubRepository.owner.id).id
+          }
+
+          return ownerIdByRepositoryId
+        }, {}),
+    }
   }
 
-  async synchronizeOrganization(githubOrganization) {
+  async synchronizeOrganization(githubOrganization) { // eslint-disable-line class-methods-use-this
```
Comment (oliviertassinari) [inline src/modules/synchronizer/GitHubSynchronizer.js]: Why not moving the function outside of the class?

File: src/review/routes/profile/Details.js [hunk 4]
```diff
@@ -1,20 +1,32 @@
...
 import Text from 'material-ui/Text'
+import Button from 'material-ui/Button'
+import Link from 'modules/components/Link'
 import ViewContainer from 'modules/components/ViewContainer'
 import ScrollView from 'modules/components/ScrollView'
 import LayoutBody from 'modules/components/LayoutBody'
 import ReviewAppBar from 'review/modules/AppBar/AppBar'
 
-function ProfileDetails(props) {
+function ProfileDetails({ user }) {
```
Comment (oliviertassinari) [inline src/review/routes/profile/Details.js]: 🙈 😛

File: src/server/routes/www.js [hunk 5]
```diff
@@ -48,24 +48,22 @@ router.use(passport.session())
 configurePassport(passport)
 
 // GraphQL
-router.use('/graphql', graphqlMiddleware())
+router.use('/graphql', graphqlMiddleware());
```
Comment (oliviertassinari) [inline src/server/routes/www.js]: `;`

File: src/server/routes/configurePassport.js [hunk 6]
```diff
@@ -13,52 +13,50 @@ function getDataFromProfile(profile) {
...
 
+  passport.serializeUser((user, done) => done(null, user.id))
   passport.deserializeUser(async (id, done) => {
     try {
-      const users = await User
-        .query()
-        .where({ id })
-
-      done(null, users[0])
+      const [user] = await User.query().where({ id })
```
Comment (oliviertassinari) [inline src/server/routes/configurePassport.js]:
```js
const user = await User.query().findById(id)
```

File: src/review/routes/profile/Details.js [hunk 7]
```diff
@@ -1,20 +1,32 @@
...
   return (
     <ViewContainer>
       <ReviewAppBar />
       <ScrollView>
         <LayoutBody margin>
           <Text type="display1" component="h2" gutterBottom>
-            {props.user.name}
+            {user.name}
           </Text>
+          {!user.privateSync && (
```
Comment (oliviertassinari) [inline src/review/routes/profile/Details.js]: What about always displaying it?

Comment (neoziro) [inline src/review/routes/profile/Details.js]: Because it doesn't make sense, if you enable it, then the scope is added.

Comment (neoziro) [inline src/review/routes/profile/Details.js]: But you are right, it can be useful because if you revoke and retry, I don't think I handle it.

File: src/modules/synchronizer/GitHubSynchronizer.js (hunk 2 above)
Comment (neoziro) [inline src/modules/synchronizer/GitHubSynchronizer.js]: TODO in refactoring, tired 😴

File: src/modules/synchronizer/GitHubSynchronizer.js (hunk 3 above)
Comment (neoziro) [inline src/modules/synchronizer/GitHubSynchronizer.js]: Because I prefer to have all functions in the class for lisibility.

File: src/review/routes/profile/Details.js (hunk 7 above)
Comment (neoziro) [inline src/review/routes/profile/Details.js]: I think it's better to have the action just one time.

File: src/modules/synchronizer/GitHubSynchronizer.js (hunk 1 above)
Comment (neoziro) [inline src/modules/synchronizer/GitHubSynchronizer.js]: I don't know 😴
